services:
  web:
    build:
      dockerfile: Dockerfile.dev
    ports:
      - '4000:4000'
    volumes:
      - .:/app
    environment:
      DB_HOST: db
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
